app_id: 81bd521a-2601-4811-b925-aa732403baae
app_secret: 9xqD3=Zjk92PpECW@cnGgszAz-:CZ6RK
redirect: http://localhost:8000/study/callback
scopes: openid profile offline_access user.read calendars.read Files.Read.All  Sites.Read.All 
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token